Repository mbta/skate, pull requests merged in 2023-10, with the labels that each got.

#2241 fix: reload page when channel join fails due to authentication
  assets/src/hooks/useChannel.ts
  assets/tests/hooks/useChannel.test.ts
  assets/tests/testHelpers/socketHelpers.ts
Labels: deploy-to-dev-green

#2247 Use FullStory browser API package
  assets/package-lock.json
  assets/package.json
  assets/src/app.tsx
  assets/src/components/inputModals/createPresetModal.tsx
  assets/src/components/inputModals/deletePresetModal.tsx
  assets/src/components/inputModals/overwritePresetModal.tsx
  assets/src/components/ladderPage.tsx
  assets/src/components/lateView.tsx
  assets/src/components/map/controls/StreetViewSwitch.tsx
  assets/src/components/map/controls/recenterControl.tsx
  assets/src/components/map/markers/stopMarker.tsx
  assets/src/components/mapMarkers.tsx
  assets/src/components/mapPage.tsx
  assets/src/components/mapPage/mapDisplay.tsx
  assets/src/components/nav/bottomNavMobile.tsx
  assets/src/components/nav/leftNav.tsx
  assets/src/components/notificationCard.tsx
  assets/src/components/oldSearchForm.tsx
  assets/src/components/presets.tsx
  assets/src/components/propertiesPanel/crowdingDiagram.tsx
  assets/src/components/propertiesPanel/miniMap.tsx
  assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
  assets/src/components/streetViewButton.tsx
  assets/src/components/swingsView.tsx
  assets/src/helpers/fullStory.ts
  assets/src/hooks/useGarageFilter.tsx
  assets/src/hooks/useNotificationsReducer.ts
  assets/src/hooks/useVehicleForNotification.ts
  assets/src/skate.d.ts
  assets/tests/components/inputModals/createPresetModal.test.tsx
  assets/tests/components/inputModals/deletePresetModal.test.tsx
  assets/tests/components/inputModals/overwritePresetModal.test.tsx
  assets/tests/components/ladderPage.test.tsx
  assets/tests/components/lateView.test.tsx
  assets/tests/components/map.test.tsx
  assets/tests/components/mapMarkers.test.tsx
  assets/tests/components/mapPage.test.tsx
  assets/tests/components/mapPage/mapDisplay.test.tsx
  assets/tests/components/nav/bottomNavMobile.test.tsx
  assets/tests/components/nav/leftNav.test.tsx
  assets/tests/components/notificationCard.test.tsx
  assets/tests/components/oldSearchForm.test.tsx
  assets/tests/components/presets.test.tsx
  assets/tests/components/propertiesPanel/crowdingDiagram.tippy.test.tsx
  assets/tests/components/propertiesPanel/miniMap.test.tsx
  assets/tests/components/propertiesPanel/vehiclePropertiesPanel.test.tsx
  assets/tests/components/streetViewButton.test.tsx
  assets/tests/components/swingsView.test.tsx
  assets/tests/contexts/notificationsContext.test.tsx
  assets/tests/helpers/fullStory.test.ts
  assets/tests/hooks/useGarageFilter.test.tsx
  assets/tests/hooks/useNotificationsReducer.test.tsx
  assets/tests/hooks/useVehicleForNotification.test.tsx
  assets/tests/testHelpers/mockHelpers.ts
  config/config.exs
  lib/skate/application.ex
  lib/skate_web/templates/layout/_fullstory.html.eex
  test/skate_web/controllers/page_controller_test.exs
Labels: deploy-to-dev-blue

#2248 cleanup: remove `laboratory` and convert `laboratory` feature flags to test groups
  assets/src/components/nav/leftNav.tsx
  assets/src/laboratoryFeatures.ts
  assets/src/userInTestGroup.ts
  assets/tests/components/notifications.test.tsx
  assets/tests/components/rightPanel.test.tsx
  assets/tests/components/settingsPage.test.tsx
  assets/tests/contexts/notificationsContext.test.tsx
  assets/tests/laboratoryFeatures.test.ts
  assets/tests/models/vehicle.test.ts
  config/config.exs
  lib/skate_web/controllers/page_controller.ex
  lib/skate_web/router.ex
  lib/skate_web/templates/admin/index.html.eex
  lib/skate_web/templates/page/index.html.eex
  mix.exs
  mix.lock
  test/skate_web/controllers/admin_controller_test.exs
  test/skate_web/router_test.exs
Labels: deploy-to-dev-green

#2253 feat: Sentry - FullStory integration
  .envrc.template
  assets/package-lock.json
  assets/package.json
  assets/src/app.tsx
  assets/src/helpers/sentryInit.ts
  assets/src/skate.d.ts
  assets/tests/helpers/sentryInit.test.ts
  config/config.exs
  lib/skate/application.ex
  lib/skate_web/controllers/page_controller.ex
  lib/skate_web/templates/layout/_sentry.html.eex
  test/skate_web/controllers/page_controller_test.exs
Labels: deploy-to-dev-blue

#2255 Minor Sentry cleanup
  assets/src/skate.d.ts
  lib/skate_web/templates/layout/_sentry.html.eex
Labels: deploy-to-dev-blue

#2257 fix: sort through-routed trips numerically
  lib/schedule/hastus/trip.ex
  test/schedule/hastus/trip_test.exs
Labels: deploy-to-dev-blue

#2259 fix: don't use HASTUS start / end place for through-routed trips
  assets/src/models/minischeduleData.ts
  lib/schedule/hastus/trip.ex
  test/schedule/hastus/trip_test.exs
Labels: deploy-to-dev-blue

#2254 [PROTOTYPE] feat(ts/mapPage): respect user's current zoom in follower and initially disable follower on route _selection_
  assets/src/components/map/follower.tsx
  assets/src/components/mapPage.tsx
  assets/src/components/mapPage/mapDisplay.tsx
  assets/tests/components/mapPage.test.tsx
  assets/tests/components/mapPage/mapDisplay.test.tsx
Labels: deploy-to-dev-green, do-not-merge

#2263 Link VPC run number to VPP
  assets/css/_skate_ui.scss
  assets/src/components/app.tsx
  assets/src/components/mapPage.tsx
  assets/src/components/mapPage/vehiclePropertiesCard.tsx
  assets/src/components/propertiesPanel.tsx
  assets/src/components/propertiesPanel/ghostPropertiesPanel.tsx
  assets/src/components/propertiesPanel/header.tsx
  assets/src/components/propertiesPanel/staleDataPropertiesPanel.tsx
  assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
  assets/src/components/rightPanel.tsx
  assets/src/userInTestGroup.ts
  assets/src/util/mapMode.ts
  assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap
  assets/tests/components/mapPage.test.tsx
  assets/tests/components/propertiesPanel.test.tsx
  assets/tests/components/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap
  assets/tests/components/propertiesPanel/__snapshots__/header.test.tsx.snap
  assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
  assets/tests/components/propertiesPanel/ghostPropertiesPanel.test.tsx
  assets/tests/components/propertiesPanel/header.test.tsx
  assets/tests/components/propertiesPanel/staleDataPropertiesPanel.test.tsx
  assets/tests/components/propertiesPanel/vehiclePropertiesPanel.test.tsx
  assets/tests/testHelpers/selectors/components/closeButton.ts
  assets/tests/util/mapMode.test.ts
Labels: deploy-to-dev-blue

#2267 feat: change application supervision strategy
  config/config.exs
  lib/skate/application.ex
Labels: deploy-to-dev-green
