Repository mbta/skate, pull requests merged in 2024-03, with the labels that each got.

#2448 Style detour close modal
  assets/src/components/detours/diversionPage.tsx
Labels: deploy-to-dev-green, chromatic

#2457 feat(storybook): Add stories for DetourMap
  assets/stories/skate-components/detours/detourMap.stories.tsx
Labels: chromatic

#2469 feat: map button components
  assets/css/app.scss
  assets/css/map/controls/_map_button.scss
  assets/src/components/map/controls/mapButton.tsx
  assets/src/helpers/bsIcons.tsx
  assets/stories/skate-components/map/controls/mapButton.stories.tsx
Labels: chromatic

#2458 feat: Update detour-shape weight and color to match hi-fi design
  assets/css/detours/_detour_map.scss
  assets/src/components/detours/detourMap.tsx
Labels: chromatic

#2467 feat: Style cursor for placing the end-point of a detour
  assets/css/detours/_detour_map.scss
  assets/src/components/detours/detourMap.tsx
Labels: chromatic

#2471 feat: hifi undo / clear buttons
  assets/src/components/detours/detourMap.tsx
  assets/src/helpers/bsIcons.tsx
  assets/tests/components/map/controls/mapButton.test.tsx
Labels: deploy-to-dev-blue, chromatic

#2468 feat: Update start, end, and way- point markers on the detour map
  assets/css/color/_tokens_2024.scss
  assets/css/detours/_detour_map.scss
  assets/src/components/detours/detourMap.tsx
  assets/stories/skate-components/detours/markers/endIcon.stories.tsx
  assets/stories/skate-components/detours/markers/startIcon.stories.tsx
  assets/stories/skate-components/detours/markers/waypointIcon.stories.tsx
Labels: chromatic

#2474 fix: Fix detour shape color
  assets/css/detours/_detour_map.scss
Labels: chromatic

#2473 feat: add connection points to finished detour panel
  assets/src/components/detours/diversionPage.tsx
  assets/src/hooks/useDetour.ts
  assets/src/models/detour.ts
  assets/src/models/finishedDetour.ts
  assets/src/models/stopData.ts
  assets/tests/api.test.ts
  assets/tests/components/detours/diversionPage.test.tsx
  assets/tests/factories/finishedDetourFactory.ts
  assets/tests/hooks/useDetour.test.ts
  lib/skate/detours/missed_stops.ex
  lib/skate_web/controllers/detours_controller.ex
  test/skate/detours/missed_stops_test.exs
  test/skate_web/controllers/detours_controller_test.exs
Labels: deploy-to-dev-green

#2466 feat: Add cursor for placing a waypoint
  assets/css/detours/_detour_map.scss
  assets/src/components/detours/detourMap.tsx
  assets/src/components/detours/diversionPage.tsx
  assets/src/hooks/useDetour.ts
  assets/stories/skate-components/detours/detourMap.stories.tsx
  assets/tests/hooks/useDetour.test.ts
Labels: chromatic

#2487 feedback(design):fix(css/diversionPage): make panel width the larger of `300px` or `22.5%` of the screen
  assets/css/_diversion_page.scss
Labels: chromatic

#2464 general fixes for routing and instructions
  lib/skate/open_route_service_api.ex
  lib/skate/open_route_service_api/directions_request.ex
  test/skate/open_route_service_api_test.exs
  test/skate_web/controllers/detour_route_controller_test.exs
Labels: deploy-to-dev-blue

#2507 feat(ex/skate/open_route_service_api): send 40ft bus info to ORS for HGV profile routing
  lib/skate/open_route_service_api/directions_request.ex
  test/skate_web/controllers/detour_route_controller_test.exs
Labels: deploy-to-dev-blue, deploy-to-dev-green
