Repository mbta/skate, pull requests merged in 2024-01, with the labels that each got.

#2350 Remove old search mode code
  assets/src/components/app.tsx
  assets/src/components/map.tsx
  assets/src/components/mapPage.tsx
  assets/src/components/nav/topNavMobile.tsx
  assets/src/components/oldSearchForm.tsx
  assets/src/components/propertiesPanel/miniMap.tsx
  assets/src/components/searchPage.tsx
  assets/src/components/searchResults.tsx
  assets/src/hooks/useAutocompleteResults.ts
  assets/src/hooks/useSearchResults.ts
  assets/src/hooks/useSearchResultsByCategory.ts
  assets/src/navLinkData.ts
  assets/src/userInTestGroup.ts
  assets/src/util/mapMode.ts
  assets/tests/components/__snapshots__/app.test.tsx.snap
  assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
  assets/tests/components/__snapshots__/mapPage.test.tsx.snap
  assets/tests/components/__snapshots__/oldSearchForm.test.tsx.snap
  assets/tests/components/__snapshots__/searchPage.test.tsx.snap
  assets/tests/components/app.test.tsx
  assets/tests/components/map.test.tsx
  assets/tests/components/mapPage.test.tsx
  assets/tests/components/nav.test.tsx
  assets/tests/components/nav/bottomNavMobile.test.tsx
  assets/tests/components/nav/leftNav.test.tsx
  assets/tests/components/oldSearchForm.test.tsx
  assets/tests/components/propertiesPanel.test.tsx
  assets/tests/components/propertiesPanel/miniMap.test.tsx
  assets/tests/components/propertiesPanel/vehiclePropertiesPanel.test.tsx
  assets/tests/components/searchPage.test.tsx
  assets/tests/components/searchResults.test.tsx
  assets/tests/hooks/useSearchResults.test.ts
  assets/tests/hooks/useSearchResultsByCategory.test.ts
  assets/tests/util/mapMode.test.ts
  lib/realtime/server.ex
  lib/skate_web/channels/vehicle_channel.ex
  lib/skate_web/channels/vehicles_channel.ex
  lib/skate_web/channels/vehicles_search_channel.ex
  test/realtime/server_test.exs
  test/skate_web/channels/vehicle_channel_test.exs
  test/skate_web/channels/vehicles_channel_test.exs
Labels: deploy-to-dev-green

#2367 feat(skate/detours/turn-by-turn): add turn-by-turn directions to detours page
  assets/src/components/detours/diversionPage.tsx
  assets/src/components/dummyDetourPage.tsx
  assets/src/detour.ts
  assets/src/hooks/useDetour.tsx
  assets/src/models/detourShapeData.ts
  assets/tests/factories/detourShapeFactory.ts
  assets/tests/factories/shapePointFactory.ts
  assets/tests/hooks/useDetour.test.ts
  lib/skate/open_route_service_api.ex
  lib/skate/open_route_service_api/directions_response.ex
  test/skate/open_route_service_api_test.exs
  test/skate_web/controllers/detour_route_controller_test.exs
  test/support/factory.ex
Labels: chromatic

#2370 Initial fixes to tab order
  assets/src/components/detours/detourMap.tsx
  assets/src/components/ladderPage.tsx
  assets/src/components/map/controls/StreetViewSwitch.tsx
  assets/src/components/map/controls/customControl.tsx
  assets/src/components/nav.tsx
  assets/src/components/routePicker.tsx
  assets/tests/components/__snapshots__/app.test.tsx.snap
  assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
  assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
  assets/tests/components/__snapshots__/mapPage.test.tsx.snap
  assets/tests/components/__snapshots__/routePicker.test.tsx.snap
  assets/tests/components/map/controls/customControl.test.tsx
Labels: deploy-to-dev-blue

#2372 feat: green dot cursor for existing route shape
  assets/css/detours/_detour_map.scss
  assets/src/components/detours/detourMap.tsx
  assets/tests/components/detours/detourMap.test.tsx
Labels: deploy-to-dev-green
