Repository mbta/skate, pull requests merged in 2024-02, with the labels that each got.

#2380 feat: add logout for keycloak
  lib/skate_web/controllers/auth_controller.ex
  lib/skate_web/router.ex
  test/skate_web/controllers/auth_controller_test.exs
  test/support/factory.ex
Labels: deploy-to-dev-blue

#2390 Ad-hoc update of some npm deps
  assets/package-lock.json
Labels: deploy-to-dev-blue

#2365 feat(css/colors): add new eggplant and gray tokens
  assets/css/_ui_kit.scss
  assets/css/bootstrap/_map_overrides.scss
  assets/css/bootstrap/_variable_overrides.scss
  assets/css/color/_definitions.scss
  assets/css/color/_tokens_2021.scss
  assets/css/color/_tokens_2024.scss
  assets/css/exports/colors/all-colors.eggplant.module.scss
  assets/css/exports/colors/all-colors.gray.module.scss
  assets/css/exports/colors/all-colors.kiwi.module.scss
  assets/css/exports/colors/all-colors.lemon.module.scss
  assets/css/exports/colors/all-colors.strawberry.module.scss
  assets/css/exports/colors/system-state.module.scss
  assets/css/typography/_variables.scss
Labels: chromatic

#2388 CircleButton and UserAvatar components
  assets/css/_circle_button.scss
  assets/css/_user_avatar.scss
  assets/css/app.scss
  assets/src/components/circleButton.tsx
  assets/src/components/userAvatar.tsx
  assets/stories/skate-components/circleButton.stories.tsx
  assets/stories/skate-components/userAvatar.stories.tsx
  assets/tests/components/circleButton.test.tsx
  assets/tests/components/userAvatar.test.tsx
Labels: chromatic

#2383 feat: Add <LoggedInAs /> component
  assets/css/_logged_in_as.scss
  assets/css/app.scss
  assets/src/components/loggedInAs.tsx
  assets/stories/skate-components/identity/loggedInAs.stories.tsx
Labels: chromatic

#2391 feat(ts/components/navMenu): upgrade mobile nav to use bootstrap components
  assets/css/bootstrap.scss
  assets/src/components/nav/navMenu.tsx
  assets/src/helpers/bsIcons.tsx
  assets/stories/skate-components/navMenu.stories.tsx
  assets/tests/components/nav/navMenu.test.tsx
Labels: chromatic

#2392 feat(ts/components/navMenu): add logout link to mobile nav
  assets/src/components/nav/navMenu.tsx
  assets/src/helpers/bsIcons.tsx
  assets/tests/components/nav/navMenu.test.tsx
Labels: chromatic

#2394 feat(ts/compmonents/navMenu): add `<LoggedInAs/>` to Mobile `<NavMenu/>`
  assets/src/components/loggedInAs.tsx
  assets/src/components/nav/navMenu.tsx
  assets/tests/components/nav/navMenu.test.tsx
Labels: chromatic

#2395 Desktop logout link
  assets/css/bootstrap.scss
  assets/css/bootstrap/_polyfills.scss
  assets/src/components/nav/topNav.tsx
  assets/tests/components/nav/topNav.test.tsx
Labels: deploy-to-dev-green

#2399 feat(ex/skate_web/AuthController): redirect to mbta.com on logout
  lib/skate_web/controllers/auth_controller.ex
  test/skate_web/controllers/auth_controller_test.exs
Labels: deploy-to-dev-green

#2400 feat: "roll over" to new guardian tokens when enabling Keycloak
  lib/skate_web/auth_manager.ex
  lib/skate_web/auth_manager/pipeline.ex
  test/skate_web/auth_manager_test.exs
Labels: deploy-to-dev-green

#2406 feat: use custom validity period for Guardian token
  lib/skate_web/controllers/auth_controller.ex
Labels: deploy-to-dev-green

#2408 fix: store logout URL in user session, not guardian claims
  lib/skate_web/controllers/auth_controller.ex
  test/skate_web/controllers/auth_controller_test.exs
Labels: deploy-to-dev-blue

#2410 chore: remove fallback on signout URL from Guardian claims
  lib/skate_web/controllers/auth_controller.ex
  test/skate_web/controllers/auth_controller_test.exs
Labels: deploy-to-dev-blue

#2411 Log user information during socket connection
  lib/report.ex
  lib/report/user_info.ex
  lib/skate_web/channels/user_socket.ex
  test/report/user_info_test.exs
  test/report_test.exs
  test/skate_web/channels/user_socket_test.exs
Labels: deploy-to-dev-blue

#2422 feat: Add ability to clear entire detour in one go
  assets/src/components/detours/detourMap.tsx
  assets/src/components/detours/diversionPage.tsx
  assets/src/hooks/useDetour.tsx
  assets/tests/components/detours/detourMap.test.tsx
  assets/tests/components/detours/diversionPage.test.tsx
  assets/tests/hooks/useDetour.test.ts
Labels: deploy-to-dev-blue, chromatic

#2424 feat: Highlight and widen clickable area on original route shape for detour map
  assets/css/detours/_detour_map.scss
  assets/src/components/detours/detourMap.tsx
Labels: deploy-to-dev-green

#2432 fix(css+sb/diversion-panel): fix panels not expanding in stories
  assets/css/_diversion_page.scss
  assets/stories/skate-components/detours/diversionPanel.stories.tsx
Labels: chromatic

#2429 feat(ts/components/diversionPage): add share detour panel
  assets/css/_diversion_page.scss
  assets/css/bootstrap.scss
  assets/src/components/detours/detourFinishedPanel.tsx
  assets/src/components/detours/diversionPage.tsx
  assets/src/helpers/bsIcons.tsx
  assets/stories/skate-components/detours/detourFinishedPanel.stories.tsx
  assets/tests/components/detours/diversionPage.test.tsx
  assets/tests/testHelpers/selectors/components/detours/diversionPage.tsx
Labels: chromatic
