Repository mbta/skate, pull requests merged in 2024-05, with the labels that each got.

#2575 feat: Add a placeholder minimal-route-ladders page
  assets/src/components/app.tsx
  assets/src/components/minimalLadderPage.tsx
  assets/src/userInTestGroup.ts
  assets/stories/skate-components/pages/minimalLadderPage.stories.tsx
  lib/skate_web/router.ex
Labels: chromatic

#2590 cleanup(gh/actions/ci): use `--prefix=assets` instead of `pushd` & `popd`
  .github/workflows/ci.yml
Labels: deploy-to-dev-blue

#2592 chore(ex/ueberauth_oidcc): update from `0.3.1` ~> `0.4.0`
  mix.exs
  mix.lock
Labels: deploy-to-dev-green

#2594 feat: Add a banner on the admin pages indicating what environment you're in
  config/runtime.exs
  lib/skate_web/components/core_components.ex
  lib/skate_web/components/layouts/barebones.html.heex
  test/skate_web/controllers/admin_controller_test.exs
Labels: deploy-to-dev-blue, deploy-to-dev-green

#2595 feat: Change desktop nav icons to bootstrap
  assets/css/nav/_left_nav.scss
  assets/src/components/nav/leftNav.tsx
  assets/src/helpers/bsIcons.tsx
  assets/tests/components/__snapshots__/app.test.tsx.snap
  assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
Labels: chromatic

#2604 feat(ex/components/app): disable `.drift` in local dev by default
  config/dev.exs
  lib/skate_web/components/layouts.ex
  lib/skate_web/components/layouts/app.html.heex
Labels: deploy-to-dev-blue

#2600 feat: Updated route-pill with a new size, currently called "large-format"
  assets/css/_route_pill.scss
  assets/src/components/detours/diversionPanel.tsx
  assets/src/components/routePill.tsx
  assets/stories/skate-components/routePill.stories.tsx
Labels: chromatic
