Repository mbta/skate, pull requests merged in 2025-01, with the labels that each got.

#2918 tweak: Add routepattern signifier in detour dropdown
  assets/src/components/routeLadder.tsx
  assets/src/models/detoursList.ts
  assets/tests/components/detours/detourListPage.test.tsx
  assets/tests/components/ladderPage.test.tsx
  assets/tests/components/routeLadder.test.tsx
  assets/tests/factories/detourListFactory.ts
  lib/skate/detours/detour.ex
  test/skate_web/controllers/detours_controller_test.exs
  test/support/factories/detour_factory.ex
Labels: deploy-to-dev-green

#2923 feat(ts/ActiveDetourPanel): add detour properties to activated panel
  assets/css/_diversion_page.scss
  assets/src/components/detours/detourPanels/activeDetourPanel.tsx
  assets/src/components/detours/diversionPage.tsx
  assets/stories/skate-components/detours/activeDetourPanel.stories.tsx
  assets/tests/components/detours/diversionPage.activate.test.tsx
Labels: chromatic

#2928 feat: Change detour duration modal
  assets/src/components/detours/activateDetourModal.tsx
  assets/src/components/detours/changeDurationModal.tsx
  assets/src/components/detours/diversionPage.tsx
  assets/src/hooks/useDetour.ts
  assets/src/models/createDetourMachine.ts
  assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
  assets/tests/components/detours/diversionPage.editDuration.test.tsx
  assets/tests/factories/detourListFactory.ts
  assets/tests/factories/detourStateMachineFactory.ts
Labels: deploy-to-dev-blue
